services:

  couchbase_docker_db:
    image: couchbase
    container_name: couchbase_docker
    ports:
      - 8891:8091
      - 8892:8092
      - 8893:8093
      - 11210:11210
      - 11211:11211

  request-service:
    image: request-service
    ports:
    - 8081:8080
    build:
      context: request-service
      dockerfile: Dockerfile
    depends_on:
      - couchbase_docker_db
    environment:
      spring.profiles.active: prod

  3rd-party-agent:
    image: 3rd-party-agent
    ports:
    - 8082:8082
    build:
      context: 3rd-party-agent
      dockerfile: Dockerfile
    depends_on:
      - couchbase_docker_db
    environment:
      spring.profiles.active: prod

  sintezator-service:
    image: sintezator-service
    ports:
      - 8078:8078
    build:
      context: sintezator-service
      dockerfile: Dockerfile
    depends_on:
      - couchbase_docker_db
    environment:
      spring.profiles.active: prod

  wiremock-server:

    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./mappings:/wiremock/mappings
    ports:
      - 15500:15500

  redis:
    image: redis
    ports:
      - '6379:6379'


