spring:
  couchbase:
    connection-string: localhost:11210
    username: user
    password: couchbase
    env:
      ssl:
        enabled: false
  data:
    couchbase:
      bucket-name: report

wiremock:
  server:
    url: http://localhost:15500/report